In [40]:
import numpy as np
import random

# Максимум 5 баллов - по ~0.7 баллов за задание

### 1. Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. 
Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [50]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]], dtype=int)
X_1 = np.array([[random.randint(0, 3) for i in range(10)] for j in range(7)])
X_2 = np.array([[random.randint(0, 3) for i in range(70)] for j in range(100)])
X_3 = np.array([[random.randint(0, 3) for i in range(1000)] for j in range(1000)])

#### 1.1

In [57]:
np.prod(np.diag(X)[np.diag(X).nonzero()])

3

In [58]:
%%timeit
np.prod(np.diag(X_1)[np.diag(X_1).nonzero()])

7.58 µs ± 94.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
%%timeit
np.prod(np.diag(X_2)[np.diag(X_2).nonzero()])

8.06 µs ± 51.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [60]:
%%timeit
np.prod(np.diag(X_3)[np.diag(X_3).nonzero()])

13.4 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 1.2

In [53]:
res = 1
for i in range(min(X.shape)):
    if X[i, i] != 0:
        res *= X[i, i]
res

3

In [65]:
%%timeit
res = 1
for i in range(min(X_1.shape)):
    if X_1[i, i] != 0:
        res *= X_1[i, i]
res

2.72 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [55]:
%%timeit
res = 1
for i in range(min(X_2.shape)):
    if X_2[i, i] != 0:
        res *= X_2[i, i]
res

23.8 µs ± 659 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [56]:
%%timeit
res = 1
for i in range(min(X_3.shape)):
    if X_3[i, i] != 0:
        res *= X_3[i, i]
res

/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in long_scalars
  after removing the cwd from sys.path.


377 µs ± 8.52 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 1.3

In [61]:
np.prod(list(filter(lambda x: x != 0, np.diag(X))))

3

In [62]:
%%timeit
np.prod(list(filter(lambda x: x != 0, np.diag(X_1))))

10.5 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
%%timeit
np.prod(list(filter(lambda x: x != 0, np.diag(X_2))))

23.1 µs ± 515 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [64]:
%%timeit
np.prod(list(filter(lambda x: x != 0, np.diag(X_3))))

210 µs ± 2.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Вывод: векторизованный вариант в разы лучше

### 2. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).

In [67]:
import random
X_1 = np.matrix(np.arange(1, 10, 1).reshape(-1, 3))
X_2 = np.matrix(np.arange(1, 91, 1).reshape(-1, 3))
X_3 = np.matrix(np.arange(1, 901, 1).reshape(-1, 3))
i_1 = np.array([random.randint(0, 2) for x in range(X_1.size)])
i_2 = np.array([random.randint(0, 29) for x in range(X_2.size)])
i_3 = np.array([random.randint(0, 299) for x in range(X_3.size)])
j_1 = np.array([random.randint(0, 2) for x in range(X_1.size)])
j_2 = np.array([random.randint(0, 2) for x in range(X_2.size)])
j_3 = np.array([random.randint(0, 2) for x in range(X_3.size)])

#### 2.1

In [69]:
np.array([X_1[i_1[n], j_1[n]] for n in range(i_1.size)])

array([2, 1, 8, 3, 9, 9, 6, 5, 6])

In [70]:
%%timeit
np.array([X_1[i_1[n], j_1[n]] for n in range(i_1.size)])

7.69 µs ± 96.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [71]:
%%timeit
np.array([X_2[i_2[n], j_2[n]] for n in range(i_2.size)])

70.8 µs ± 1.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [72]:
%%timeit
np.array([X_3[i_3[n], j_3[n]] for n in range(i_3.size)])

683 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 2.2

In [73]:
np.array(X_1[i_1, j_1])[0]

array([2, 1, 8, 3, 9, 9, 6, 5, 6])

In [74]:
%%timeit
np.array(X_1[i_1, j_1])[0]

4.38 µs ± 26.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
%%timeit
np.array(X_2[i_2, j_2])[0]

4.79 µs ± 39 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [76]:
%%timeit
np.array(X_3[i_3, j_3])[0]

9.03 µs ± 57.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 2.3

In [77]:
res = []
for n in range(X_1.size):
    res.append(X_1[i_1[n], j_1[n]])
np.array(res)

array([2, 1, 8, 3, 9, 9, 6, 5, 6])

In [78]:
%%timeit
res = []
for n in range(X_1.size):
    res.append(X_1[i_1[n], j_1[n]])
np.array(res)

7.87 µs ± 265 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [79]:
%%timeit
res = []
for n in range(X_2.size):
    res.append(X_2[i_2[n], j_2[n]])
np.array(res)

70.7 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [80]:
%%timeit
res = []
for n in range(X_3.size):
    res.append(X_3[i_3[n], j_3[n]])
np.array(res)

697 µs ± 18.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Вывод: векторизованный метод в разы лучше

### 3. Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество. 
Для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [90]:
x = np.array([1, 2, 4])
y = np.array([4, 2, 1, 2])
x_1_size = random.randint(7, 8)
x_1 = np.array([1 for x in range(x_1_size)] + [0 for x in range(10-x_1_size)])
y_1 = np.array([0, 0] + [1 for x in range(8)])
x_2_size = random.randint(79, 80)
x_2 = np.array([1 for x in range(x_2_size)] + [0 for x in range(100-x_2_size)])
y_2 = np.array([0 for x in range(20)] + [1 for x in range(80)])
x_3_size = random.randint(799, 800)
x_3 = np.array([1 for x in range(x_3_size)] + [0 for x in range(1000-x_3_size)])
y_3 = np.array([0 for x in range(200)] + [1 for x in range(800)])

#### 3.1

In [94]:
x.size == y.size and all(np.equal(np.sort(x), np.sort(y)))

False

In [23]:
%%timeit
x_1.size == y_1.size and all(np.equal(np.sort(x_1), np.sort(y_1)))

4 µs ± 23.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
%%timeit
x_2.size == y_2.size and all(np.equal(np.sort(x_2), np.sort(y_2)))

5.66 µs ± 35 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
%%timeit
x_3.size == y_3.size and all(np.equal(np.sort(x_3), np.sort(y_3)))

23 µs ± 211 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 3.2

In [89]:
sorted(x) == sorted(y)

False

In [27]:
%%timeit
sorted(x_1) == sorted(y_1)

2.23 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
sorted(x_2) == sorted(y_2)

9.43 µs ± 29.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%%timeit
sorted(x_3) == sorted(y_3)

76.4 µs ± 416 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 3.3

Сортировка выбором (неэффективно, да)

In [30]:
for i in range(x.size):
    m = i
    for j in range(i+1, x.size):
        if x[j] > x[m]:
            m = j
    buf = x[i]
    x[i] = x[m]
    x[m] = buf
for i in range(y.size):
    m = i
    for j in range(i+1, y.size):
        if y[j] > y[m]:
            m = j
    buf = y[i]
    y[i] = y[m]
    y[m] = buf
all(x == y)

True

In [31]:
%%timeit
for i in range(x_1.size):
    m = i
    for j in range(i+1, x_1.size):
        if x_1[j] > x_1[m]:
            m = j
    buf = x_1[i]
    x_1[i] = x_1[m]
    x_1[m] = buf
for i in range(y_1.size):
    m = i
    for j in range(i+1, y_1.size):
        if y_1[j] > y_1[m]:
            m = j
    buf = y_1[i]
    y_1[i] = y_1[m]
    y_1[m] = buf
all(x_1 == y_1)

23.4 µs ± 253 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [32]:
%%timeit
for i in range(x_2.size):
    m = i
    for j in range(i+1, x_2.size):
        if x_2[j] > x_2[m]:
            m = j
    buf = x_2[i]
    x_2[i] = x_2[m]
    x_2[m] = buf
for i in range(y_2.size):
    m = i
    for j in range(i+1, y_2.size):
        if y_2[j] > y_2[m]:
            m = j
    buf = y_2[i]
    y_2[i] = y_2[m]
    y_2[m] = buf
all(x_2 == y_2)

1.51 ms ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
%%timeit
for i in range(x_3.size):
    m = i
    for j in range(i+1, x_3.size):
        if x_3[j] > x_3[m]:
            m = j
    buf = x_3[i]
    x_3[i] = x_3[m]
    x_3[m] = buf
for i in range(y_3.size):
    m = i
    for j in range(i+1, y_3.size):
        if y_3[j] > y_3[m]:
            m = j
    buf = y_3[i]
    y_3[i] = y_3[m]
    y_3[m] = buf
all(x_3 == y_3)

159 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 4. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [34]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
def new_item():
    item = random.randint(0, 1)
    if item:
        item = random.randint(1, 100)
    return item
x_1 = np.array([new_item() for i in range(10)])
x_2 = np.array([new_item() for i in range(100)])
x_3 = np.array([new_item() for i in range(1000)])

#### 4.1

In [35]:
zeroes = x == 0
x[1:][zeroes[:-1]].max()

5

In [36]:
%%timeit
zeroes = x_1 == 0
x_1[1:][zeroes[:-1]].max()

2.45 µs ± 30.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
%%timeit
zeroes = x_2 == 0
x_2[1:][zeroes[:-1]].max()

2.7 µs ± 15.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
%%timeit
zeroes = x_3 == 0
x_3[1:][zeroes[:-1]].max()

5.19 µs ± 13.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 4.2

In [39]:
max_ = x.min() - 1
for i in range(1, x.size):
    if x[i-1] == 0 and x[i] > max_:
        max_ = x[i]
max_

5

In [40]:
%%timeit
max_ = x_1.min() - 1
for i in range(1, x_1.size):
    if x_1[i-1] == 0 and x_1[i] > max_:
        max_ = x_1[i]
max_

3.7 µs ± 23.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [41]:
%%timeit
max_ = x_2.min() - 1
for i in range(1, x_2.size):
    if x_2[i-1] == 0 and x_2[i] > max_:
        max_ = x_2[i]
max_

22 µs ± 272 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [42]:
%%timeit
max_ = x_3.min() - 1
for i in range(1, x_3.size):
    if x_3[i-1] == 0 and x_3[i] > max_:
        max_ = x_3[i]
max_

230 µs ± 1.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 4.3

In [43]:
max_ = int
for i in x.argsort()[::-1]:
    if i != 0 and x[i-1] == 0:
        max_ = x[i]
        break
max_

5

In [44]:
%%timeit
max_ = int
for i in x_1.argsort()[::-1]:
    if i != 0 and x_1[i-1] == 0:
        max_ = x_1[i]
        break
max_

1.03 µs ± 12.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [45]:
%%timeit
max_ = int
for i in x_2.argsort()[::-1]:
    if i != 0 and x_2[i-1] == 0:
        max_ = x_2[i]
        break
max_

1.7 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [46]:
%%timeit
max_ = int
for i in x_3.argsort()[::-1]:
    if i != 0 and x_3[i-1] == 0:
        max_ = x_3[i]
        break
max_

5.54 µs ± 24.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 5. Дан трёхмерный массив, содержащий изображение, размера (height, width, numChannels), а также вектор длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Считать реальное изображение можно при помощи функции scipy.misc.imread (если изображение не в формате png, установите пакет pillow: conda install pillow). Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [49]:
import imageio
im_1 = imageio.imread('images/amongus_10.jpg')
im_2 = imageio.imread('images/amongus_100.jpg')
im_3 = imageio.imread('images/amongus_1000.png')
coef = np.array([0.299, 0.587, 0.114])

#### 5.1

In [50]:
im_1_bw = (im_1*coef).sum(2)
imageio.imwrite('images/amongus_10_BW.jpg', im_1_bw)

Lossy conversion from float64 to uint8. Range [2.9349999999999996, 251.012]. Convert image to uint8 prior to saving to suppress this warning.


In [53]:
%%timeit
im_1_bw = (im_1*coef).sum(2)
im_1_bw

12.4 µs ± 2.91 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
%%timeit
im_2_bw = (im_2*coef).sum(2)
im_2_bw

270 µs ± 2.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
%%timeit
im_3_bw = (im_3*coef).sum(2)
im_3_bw

28.8 ms ± 518 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 5.2

In [51]:
im_2_bw = np.empty((im_2.shape[0], im_2.shape[1], 1))
for i in range(im_2.shape[0]):
    for j in range(im_2.shape[1]):
        im_2_bw[i, j, 0] = sum(im_2[i, j] * coef)
imageio.imwrite('images/amongus_100_BW.jpg', im_2_bw)

Lossy conversion from float64 to uint8. Range [0.0, 254.43]. Convert image to uint8 prior to saving to suppress this warning.


In [56]:
%%timeit
im_1_bw = np.empty((im_1.shape[0], im_1.shape[1], 1))
for i in range(im_1.shape[0]):
    for j in range(im_1.shape[1]):
        im_1_bw[i, j, 0] = sum(im_1[i, j] * coef)
im_1_bw

2.1 ms ± 99.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
%%timeit
im_2_bw = np.empty((im_2.shape[0], im_2.shape[1], 1))
for i in range(im_2.shape[0]):
    for j in range(im_2.shape[1]):
        im_2_bw[i, j, 0] = sum(im_2[i, j] * coef)
im_2_bw

106 ms ± 5.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [58]:
%%timeit
im_3_bw = np.empty((im_3.shape[0], im_3.shape[1], 1))
for i in range(im_3.shape[0]):
    for j in range(im_3.shape[1]):
        im_3_bw[i, j, 0] = sum(im_3[i, j] * coef)
im_3_bw

7.14 s ± 84.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 5.3

In [52]:
im_3_bw_modified = im_3 * coef
im_3_bw = im_3_bw_modified.sum(axis=2)
imageio.imwrite('images/amongus_1000_BW.jpg', im_3_bw)

Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.


In [59]:
%%timeit
im_1_bw_modified = im_1 * coef
im_1_bw = im_1_bw_modified.sum(axis=2)
im_1_bw

10.9 µs ± 165 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [60]:
%%timeit
im_2_bw_modified = im_2 * coef
im_2_bw = im_2_bw_modified.sum(axis=2)
im_2_bw

263 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:
%%timeit
im_3_bw_modified = im_3 * coef
im_3_bw = im_3_bw_modified.sum(axis=2)
im_3_bw

28.4 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 6. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить. 
Пример: x = np.array([2, 2, 2, 3, 3, 3, 5]). Ответ: (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [109]:
from itertools import groupby
x = np.array([2, 2, 2, 3, 3, 3, 5, 3, 3])
x_1 = np.array([random.randint(1, 3) for i in range(10)])
x_2 = np.array([random.randint(1, 3) for i in range(100)])
x_3 = np.array([random.randint(1, 3) for i in range(1000)])

#### 6.1

In [110]:
def rle(x):
    vals = []
    counts = []
    def rle_map(x, vals_=vals, counts_=counts):
        if not len(vals_):
            vals_.append(x)
            counts_.append(1)
        else:
            if x == vals_[-1]:
                counts_[-1] += 1
            else:
                vals_.append(x)
                counts_.append(1)
    list(map(rle_map, x))
    vals = np.array(vals)
    counts = np.array(counts)
    return (vals, counts)
rle(x)

(array([2, 3, 5, 3]), array([3, 3, 1, 2]))

In [111]:
%%timeit
rle(x_1)

5.15 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [112]:
%%timeit
rle(x_2)

33.9 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [113]:
%%timeit
rle(x_3)

326 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 6.2

In [114]:
def rle(a):
    return tuple(map(np.array, zip(*((key, len(tuple(group))) for key, group in groupby(a)))))
rle(x)

(array([2, 3, 5, 3]), array([3, 3, 1, 2]))

In [115]:
%%timeit
rle(x_1)

5.89 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
%%timeit
rle(x_2)

36 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [117]:
%%timeit
rle(x_3)

333 µs ± 2.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 6.3

In [118]:
def rle(x):
    vals = []
    counts = []
    def rle_map(x, vals_=vals, counts_=counts):
        if len(vals_) == 0:
            vals_.append(x)
            counts_.append(1)
        else:
            if x == vals_[-1]:
                counts_[-1] += 1
            else:
                vals_.append(x)
                counts_.append(1)
    for item in x:
        rle_map(item)
    vals = np.array(vals)
    counts = np.array(counts)
    return (vals, counts)
rle(x)

(array([2, 3, 5, 3]), array([3, 3, 1, 2]))

In [119]:
%%timeit
rle(x_1)

5.18 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [120]:
%%timeit
rle(x_2)

34.7 µs ± 775 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [121]:
%%timeit
rle(x_3)

340 µs ± 12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 7. Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравнить с функцией scipy.spatial.distance.cdist.

In [23]:
from scipy import spatial
X_1 = np.array([[random.randint(1, 10), random.randint(1, 10)] for i in range(10)])
Y_1 = np.array([[random.randint(1, 10), random.randint(1, 10)] for i in range(10)])
X_2 = np.array([[random.randint(1, 100), random.randint(1, 100)] for i in range(100)])
Y_2 = np.array([[random.randint(1, 100), random.randint(1, 100)] for i in range(100)])
X_3 = np.array([[random.randint(1, 1000), random.randint(1, 1000)] for i in range(1000)])
Y_3 = np.array([[random.randint(1, 1000), random.randint(1, 1000)] for i in range(1000)])

#### 7.1

In [24]:
def get_distances(X, Y):
    P = np.add.outer(np.sum(X**2, axis=1), np.sum(Y**2, axis=1))
    N = np.dot(X, Y.T)
    return np.sqrt(P - 2*N)
get_distances(X_1, Y_1)

array([[ 8.94427191,  8.        ,  2.82842712,  4.47213595,  5.        ,
         1.        ,  5.38516481,  7.21110255,  2.23606798,  7.21110255],
       [ 4.47213595,  2.        ,  4.47213595,  2.82842712,  1.        ,
         6.08276253,  2.23606798,  4.        ,  5.38516481,  4.        ],
       [ 7.07106781,  5.09901951,  1.41421356,  1.41421356,  2.23606798,
         3.        ,  3.60555128,  5.83095189,  2.23606798,  4.24264069],
       [ 5.        ,  6.40312424,  6.08276253,  6.08276253,  4.47213595,
         5.83095189,  2.82842712,  3.        ,  6.32455532,  8.54400375],
       [ 7.61577311,  4.24264069,  3.16227766,  1.41421356,  3.        ,
         5.38516481,  5.        ,  7.07106781,  4.12310563,  1.41421356],
       [ 6.40312424,  4.12310563,  2.23606798,  1.        ,  1.41421356,
         4.        ,  3.16227766,  5.38516481,  3.16227766,  3.60555128],
       [10.81665383,  9.21954446,  3.        ,  5.        ,  6.32455532,
         1.41421356,  7.21110255,  9.21954446

In [25]:
%%timeit
get_distances(X_1, Y_1)

15.8 µs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%%timeit
get_distances(X_2, Y_2)

101 µs ± 1.73 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
%%timeit
get_distances(X_3, Y_3)

15.8 ms ± 812 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 7.2

In [28]:
def get_distances(X, Y):
    matrix = np.empty((X.shape[0], Y.shape[0]))
    for i in range(X.shape[0]):
        for j in range(Y.shape[0]):
            matrix[i, j] = np.linalg.norm(X[i]-Y[j])
    return matrix
get_distances(X_1, Y_1)

array([[ 8.94427191,  8.        ,  2.82842712,  4.47213595,  5.        ,
         1.        ,  5.38516481,  7.21110255,  2.23606798,  7.21110255],
       [ 4.47213595,  2.        ,  4.47213595,  2.82842712,  1.        ,
         6.08276253,  2.23606798,  4.        ,  5.38516481,  4.        ],
       [ 7.07106781,  5.09901951,  1.41421356,  1.41421356,  2.23606798,
         3.        ,  3.60555128,  5.83095189,  2.23606798,  4.24264069],
       [ 5.        ,  6.40312424,  6.08276253,  6.08276253,  4.47213595,
         5.83095189,  2.82842712,  3.        ,  6.32455532,  8.54400375],
       [ 7.61577311,  4.24264069,  3.16227766,  1.41421356,  3.        ,
         5.38516481,  5.        ,  7.07106781,  4.12310563,  1.41421356],
       [ 6.40312424,  4.12310563,  2.23606798,  1.        ,  1.41421356,
         4.        ,  3.16227766,  5.38516481,  3.16227766,  3.60555128],
       [10.81665383,  9.21954446,  3.        ,  5.        ,  6.32455532,
         1.41421356,  7.21110255,  9.21954446

In [29]:
%%timeit
get_distances(X_1, Y_1)

467 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
%%timeit
get_distances(X_2, Y_2)

45.8 ms ± 430 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%%timeit
get_distances(X_3, Y_3)

4.57 s ± 44.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 7.3

In [32]:
def get_distances(X, Y):
    matrix = []
    def get_dist(*x, X_=X, Y_=Y, m=matrix):
        return m.append(np.linalg.norm(x[0][0]-x[0][1]))
    XY = [(x, y) for x in X for y in Y]
    list(map(lambda x: get_dist(x), XY))
    matrix = np.array(matrix)
    matrix = np.reshape(matrix, (X.shape[0], Y.shape[0]))
    return matrix
get_distances(X_1, Y_1)

array([[ 8.94427191,  8.        ,  2.82842712,  4.47213595,  5.        ,
         1.        ,  5.38516481,  7.21110255,  2.23606798,  7.21110255],
       [ 4.47213595,  2.        ,  4.47213595,  2.82842712,  1.        ,
         6.08276253,  2.23606798,  4.        ,  5.38516481,  4.        ],
       [ 7.07106781,  5.09901951,  1.41421356,  1.41421356,  2.23606798,
         3.        ,  3.60555128,  5.83095189,  2.23606798,  4.24264069],
       [ 5.        ,  6.40312424,  6.08276253,  6.08276253,  4.47213595,
         5.83095189,  2.82842712,  3.        ,  6.32455532,  8.54400375],
       [ 7.61577311,  4.24264069,  3.16227766,  1.41421356,  3.        ,
         5.38516481,  5.        ,  7.07106781,  4.12310563,  1.41421356],
       [ 6.40312424,  4.12310563,  2.23606798,  1.        ,  1.41421356,
         4.        ,  3.16227766,  5.38516481,  3.16227766,  3.60555128],
       [10.81665383,  9.21954446,  3.        ,  5.        ,  6.32455532,
         1.41421356,  7.21110255,  9.21954446

In [33]:
%%timeit
get_distances(X_1, Y_1)

492 µs ± 4.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
%%timeit
get_distances(X_2, Y_2)

49.5 ms ± 554 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [35]:
%%timeit
get_distances(X_3, Y_3)

4.97 s ± 40.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 7.4

In [36]:
spatial.distance.cdist(X_1, Y_1)

array([[ 8.94427191,  8.        ,  2.82842712,  4.47213595,  5.        ,
         1.        ,  5.38516481,  7.21110255,  2.23606798,  7.21110255],
       [ 4.47213595,  2.        ,  4.47213595,  2.82842712,  1.        ,
         6.08276253,  2.23606798,  4.        ,  5.38516481,  4.        ],
       [ 7.07106781,  5.09901951,  1.41421356,  1.41421356,  2.23606798,
         3.        ,  3.60555128,  5.83095189,  2.23606798,  4.24264069],
       [ 5.        ,  6.40312424,  6.08276253,  6.08276253,  4.47213595,
         5.83095189,  2.82842712,  3.        ,  6.32455532,  8.54400375],
       [ 7.61577311,  4.24264069,  3.16227766,  1.41421356,  3.        ,
         5.38516481,  5.        ,  7.07106781,  4.12310563,  1.41421356],
       [ 6.40312424,  4.12310563,  2.23606798,  1.        ,  1.41421356,
         4.        ,  3.16227766,  5.38516481,  3.16227766,  3.60555128],
       [10.81665383,  9.21954446,  3.        ,  5.        ,  6.32455532,
         1.41421356,  7.21110255,  9.21954446

In [37]:
%%timeit
spatial.distance.cdist(X_1, Y_1)

3.76 µs ± 35.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
%%timeit
spatial.distance.cdist(X_2, Y_2)

39.9 µs ± 445 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [39]:
%%timeit
spatial.distance.cdist(X_3, Y_3)

3.42 ms ± 77.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### Замечание. Можно считать, что все указанные объекты непустые (к примеру, в задаче №1 на диагонали матрицы есть ненулевые элементы).
Полезные функции NumPy: np.zeros, np.ones, np.diag, np.eye, np.arange, np.linspace, np.meshgrid,
np.random.random, np.random.randint, np.shape, np.reshape, np.transpose, np.any, np.all, np.nonzero, np.where,
np.sum, np.cumsum, np.prod, np.diff, np.min, np.max, np.minimum, np.maximum, np.argmin, np.argmax, np.unique,
np.sort, np.argsort, np.bincount, np.ravel, np.newaxis, np.dot, np.linalg.inv, np.linalg.solve.
Многие из этих функций можно использовать так: x.argmin().

# Для каждой из задач:
(a) Написать на Python + NumPy несколько вариантов кода различной эффективности. Должно быть не
менее трёх вариантов, в том числе как минимум один полностью векторизованный вариант (без циклов), и один
вариант без векторизации (с циклами). Третий вариант решения — на ваше усмотрение, например, это может быть
наиболее хорошо читаемый способ решения, или частично векторизованный вариант. Все пункты выполнять в одном google collab, разделяя их пунктами 1., 1.1, 1.2, 1.3; 2., 2.1, 2.2, 2.3; и тд.

(b) Сравнить в IPython Notebook при помощи %timeit скорость работы на нескольких тестовых наборах
РАЗНОГО размера (минимум 3, причём отличаться размеры входных данных должны минимум на порядок. Например, массивы длины 100, 1000, 10000).

(c) Проанализировать полученные данные о скорости работы разных реализаций.

(d) Получить выводы.